#paste your configuration here
nameOfRootFolder: codenjoy-clients
teamName: TeamName
playerName: Name Surname
token: secret
modelName: gpt-35-turbo-16k
modelVersion: 2024-02-01
coolDown: 4
turnsForStore: 2
stepsForRefreshRules: 5
temperature: 0.3
maxTokensOfAnswer: 400